### ISSUE TITLE
MinGW support.

### ISSUE THREAD

**Issue by tolstenko** [hunter-packages/curl#2]
### I did this
I tried to build the curl example using [mingw](https://github.com/ruslo/hunter/blob/master/examples/CURL/foo.cpp) toolchain from [polly](https://github.com/ruslo/polly). 
```
cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_TOOLCHAIN_FILE=./dependencies/polly/linux-mingw-w64.cmake
```
I know I am on osx, and I am using linux-mingw-w64.cmake , but it never failed before.

### I expected the following
I expected to work just like the command without mingw toolchain
### curl/libcurl version

I am using the latest Hunter and HunterGate. Here is the cmake used:
```
cmake_minimum_required(VERSION 3.9)

include(cmake/HunterGate.cmake)

HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.20.63.tar.gz"
    SHA1 "358385a57457e5276f9e9db6e8e2bc80c53287ad"
)

project(curltest)

hunter_add_package(curl)
find_package(curl CONFIG REQUIRED)

set(CMAKE_CXX_STANDARD 11)

add_executable(curltest main.cpp)
target_link_libraries(curltest PUBLIC CURL::libcurl)
```
### Outputs
[mingw.txt](https://github.com/hunter-packages/curl/files/1965625/mingw.txt)
[native.txt](https://github.com/hunter-packages/curl/files/1965626/native.txt)

For some reason I don't know, the linking phase is failing.

### operating system
OSX 10.13.3, XCode 9.3

**Comment by ruslo** [comment]
> set(CMAKE_CXX_STANDARD 11)

Should be set in toolchain:
* https://cgold.readthedocs.io/en/latest/tutorials/toolchain/globals/cxx-standard.html#defaults

> mingw.txt

Use `HUNTER_STATUS_DEBUG=ON`, there will be more info printed.

> For some reason I don't know, the linking phase is failing.

It's not a CURL, it's OpenSSL:
```
ar: creating archive libcrypto.a
ranlib libcrypto.a || echo Never mind.
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: warning for library: libcrypto.a the table of contents is empty (no object file members in the library define global symbols)
```

I guess wrong `ranlib` used, it should be one from MinGW tools.

Please experiment with adapting this logic:
* https://github.com/ruslo/hunter/blob/77e57b4bf5e31162f5b8fe2cc41f9efacd192501/cmake/projects/OpenSSL/schemes/url_sha1_openssl.cmake.in#L34-L42

To MinGW:
* https://github.com/ruslo/hunter/blob/77e57b4bf5e31162f5b8fe2cc41f9efacd192501/cmake/projects/OpenSSL/schemes/url_sha1_openssl.cmake.in#L44-L50

Note that `VARIABLE=VALUE ./Configure` will not work on Windows.

**Comment by tolstenko** [comment]
Hello @ruslo,

Thanks for your support. The CMake generation process worked when I inserted:

`AR=${CMAKE_AR} RANLIB=${CMAKE_RANLIB}`

to theese lines
- https://github.com/ruslo/hunter/blob/77e57b4bf5e31162f5b8fe2cc41f9efacd192501/cmake/projects/OpenSSL/schemes/url_sha1_openssl.cmake.in#L45

 and 

- https://github.com/ruslo/hunter/blob/77e57b4bf5e31162f5b8fe2cc41f9efacd192501/cmake/projects/OpenSSL/schemes/url_sha1_openssl.cmake.in#L47

But the make process still failing when I try to compile the curl demo.

This is my cmake call (I found out it is unnecessary to define CMAKE_RANLIB and CMAKE_AR here):
```
cmake -Bbuild -H. -DHUNTER_STATUS_DEBUG=ON -DMINGW=ON -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_RANLIB=`which x86_64-w64-mingw32-ranlib` -DCMAKE_AR=`which x86_64-w64-mingw32-ar` -DCMAKE_TOOLCHAIN_FILE=./dependencies/polly/linux-mingw-w64.cmake
```
[CMakeProcessOutput.txt](https://github.com/hunter-packages/curl/files/1969676/CMakeProcessOutput.txt)

All dependencies were compiled. I browsed the .hunter folder and found them. I even ran openssl.exe using wine. It worked. Thanks.

Now the last problem is: the make process is broken. Here is the output:

[makeOutput.txt](https://github.com/hunter-packages/curl/files/1969677/makeOutput.txt)

**Comment by ruslo** [comment]
> -DMINGW=ON
> -DCMAKE_RANLIB=`which x86_64-w64-mingw32-ranlib` -DCMAKE_AR=`which x86_64-w64-mingw32-ar`

From my understading these CMake variables should be set by CMake itself, I guess few tweaks for toolchain file should be applied.

> Now the last problem is: the make process is broken. Here is the output:

> /Users/tolstenko/.hunter/_Base/358385a/ff67179/6724395/Install/lib/libcrypto.a(b_addr.o):b_addr.c:(.text+0xaa): undefined reference to `__imp_getnameinfo'

Linking with `Ws2_32.lib` is missing in `FindOpenSSL.cmake` module:
* https://github.com/ruslo/hunter/blob/master/cmake/find/FindOpenSSL.cmake

**Comment by tolstenko** [comment]
My confusion misguided you, I'm sorry. Let me clarify: 
```
cmake -Bbuild -H. -DHUNTER_STATUS_DEBUG=ON -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_TOOLCHAIN_FILE=./dependencies/polly/linux-mingw-w64.cmake
```
Now generates project correctly. I changed the two lines you cited and it worked. Thank you.

With your help, I found out that just setting -lws2_32 was enough to make the make process work.

A brief recap: 
- In hunter side, I've added `AR=${CMAKE_AR} RANLIB=${CMAKE_RANLIB}` on url_sha1_openssl.cmake.in . This made the generation process work in my machine, but in order to make it work on travis, this change must be done in the hunter project. 
- I've added into my project the additional step to target_link wsock32 ws2_32. This makes the make process work for me.

Should I submit these two line changes as pull request? Or can you change it by yourself?

Thank you for your support again!

**Comment by ruslo** [comment]
> I've added AR=${CMAKE_AR} RANLIB=${CMAKE_RANLIB} on url_sha1_openssl.cmake.in

> I've added into my project the additional step to target_link wsock32 ws2_32

Please send pull request with `url_sha1_openssl.cmake.in` and `FindOpenSSL.cmake` changes.

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
